#!/bin/sh -ex
cd ${ESP8266ARDUINO}/tests/host
make FORCE32=0 ssl
make FORCE32=0 D=1 USERCFLAGS="-I ${ARDUINOLIB}/emuAsync/replacement" ULIBDIRS=${ARDUINOLIB}/emuAsync:${ARDUINOLIB}/ArduinoJson:${ARDUINOLIB}/arduinoWebSockets/  D=1 ${ARDUINOLIB}/ESPAsyncWebServer/examples/simple_server/simple_server
